### ISSUE TITLE
App failling

### ISSUE THREAD

**Issue by bacaron** [brainlife/app-wmctotrk#3]
Hello,

I tried running this app with a standard wmc output from White Matter Anatomy Segmentation app and had the following error:

Traceback (most recent call last):
  File "/N/dc2/scratch/bacaron/brainlife/5f29bb87a5b643c0c2a2bc97/5f29bb87a5b643411fa2bc9a/wmc_to_trk.py", line 111, in <module>
    wmc_to_trk(tck, wmc, t1, "trk/track.trk", "trk/info.json")
  File "/N/dc2/scratch/bacaron/brainlife/5f29bb87a5b643c0c2a2bc97/5f29bb87a5b643411fa2bc9a/wmc_to_trk.py", line 81, in wmc_to_trk
    affine_to_rasmm=affine)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/streamlines/tractogram.py", line 329, in __init__
    self.data_per_streamline = data_per_streamline
  File "/usr/local/lib/python2.7/dist-packages/nibabel/streamlines/tractogram.py", line 347, in data_per_streamline
    len(self.streamlines), {} if value is None else value)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/streamlines/tractogram.py", line 98, in __init__
    super(PerArrayDict, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/streamlines/tractogram.py", line 38, in __init__
    self.update(dict(*args, **kwargs))
  File "/usr/lib/python2.7/_abcoll.py", line 566, in update
    self[key] = other[key]
  File "/usr/local/lib/python2.7/dist-packages/nibabel/streamlines/tractogram.py", line 114, in __setitem__
    raise ValueError(msg)
ValueError: The number of values (1) should match n_elements (300238).

Maybe there's an array dimension error?

**Comment by soichih** [comment]
Thanks for reporting this problem. I will take a look.

**Comment by soichih** [comment]
I've updated the code (removed almost all the code that was there before..) Can you test it and make sure it works the way you expect it?

The app basically just convert the tck to trk, and add the wmc's classification index as streamline data (feature of .trk) under "bundle_code". I am not sure if this is the expected behavior of this App, but we can modify it if it's not.

**Comment by bacaron** [comment]
I'm testing it now. That's basically all it needs to do, right? That's the main difference between tck and trk, correct?

**Comment by bacaron** [comment]
Failed with a walltime error

**Comment by soichih** [comment]
Increased the walltime to 30mins
